#!/usr/bin/env bash
# Indefinitely writes "I am alive" to the file /tmp/my_process.
#   Pauses two seconds in between each message.

i=0
while [ "$i" -eq 0 ]
do
	echo "I am alive!" | sudo tee -a /tmp/my_process > /dev/null
	sleep 2
done
