#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd in a specified format
while read -r line
do
	username=$(echo "$line" | cut -d ':' -f 1)
	id=$(echo "$line" | cut -d ':' -f 3)
	home=$(echo "$line" | cut -d ':' -f 6)
	echo "$username:$id:$home"
done < /etc/passwd
