#!/usr/bin/env bash
# This script changes home and facebook IP addresses
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
echo '8.8.8.8      facebook.com' >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
